language: node_js

node_js:
  - node

cache: npm

script:
  - npm test

deploy:
 - provider: script
   skip_cleanup: true
   script: npm install -g serverless && sls deploy --stage staging
   on:
     all_branches: true
 - provider: script
   skip_cleanup: true
   script: npm install -g serverless && sls deploy --stage prod
   on:
     branch: master